// AUTO-GENERATED by scripts/fetch-cast.mjs. Do not edit by hand;
// re-run the script and overwrite this file if you need new movies.
//
// Each movie has a `cast` array of actors with portrait URLs from Wikipedia.
// In the Petersburg mode, each player is shown a single random actor from the
// movie's cast (no name) and the team must guess the title together.

export interface CastMember {
  name: string;
  imageUrl: string;
}

export interface Movie {
  id: string;
  title: string;
  aliases: string[];
  cast: CastMember[];
}

export const MOVIES: Movie[] = [
  {
    id: "inception",
    title: "Начало",
    aliases: [
      "Inception",
      "Начало (Inception)"
    ],
    cast: [
      {
        name: "Леонардо ДиКаприо",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/LeoPTABFI191125-28_%28cropped%29.jpg/500px-LeoPTABFI191125-28_%28cropped%29.jpg"
      },
      {
        name: "Джозеф Гордон-Левитт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Joseph_Gordon_Levitt_Sundance_Film_Festival_2026_%28cropped%29.jpg/500px-Joseph_Gordon_Levitt_Sundance_Film_Festival_2026_%28cropped%29.jpg"
      },
      {
        name: "Эллиот Пейдж",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Elliot_Page_8126099_%28cropped%29.jpg/500px-Elliot_Page_8126099_%28cropped%29.jpg"
      },
      {
        name: "Том Харди",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Tom_Hardy_by_Gage_Skidmore_in_2018.jpg/500px-Tom_Hardy_by_Gage_Skidmore_in_2018.jpg"
      },
      {
        name: "Марион Котийяр",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Marion_Cotillard_at_2019_Cannes.jpg/500px-Marion_Cotillard_at_2019_Cannes.jpg"
      },
      {
        name: "Кен Ватанабэ",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ken_Watanabe_20220615.jpg/500px-Ken_Watanabe_20220615.jpg"
      }
    ]
  },
  {
    id: "matrix",
    title: "Матрица",
    aliases: [
      "The Matrix"
    ],
    cast: [
      {
        name: "Киану Ривз",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg/500px-Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg"
      },
      {
        name: "Лоуренс Фишбёрн",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Laurence_Fishburne_at_53rd_Saturn_Awards_2026.jpg/500px-Laurence_Fishburne_at_53rd_Saturn_Awards_2026.jpg"
      },
      {
        name: "Кэрри-Энн Мосс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Carrie-Anne_Moss_May_2016.jpg/500px-Carrie-Anne_Moss_May_2016.jpg"
      },
      {
        name: "Хьюго Уивинг",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/MJK_08925_Hugo_Weaving_%28Berlinale_2018%29_bw43.jpg/500px-MJK_08925_Hugo_Weaving_%28Berlinale_2018%29_bw43.jpg"
      },
      {
        name: "Джо Пантолиано",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/JoePantolianoFeb2009.jpg/500px-JoePantolianoFeb2009.jpg"
      }
    ]
  },
  {
    id: "lotr-fellowship",
    title: "Властелин колец: Братство кольца",
    aliases: [
      "Властелин колец",
      "Братство кольца",
      "The Lord of the Rings",
      "The Fellowship of the Ring",
      "Властелин колец 1"
    ],
    cast: [
      {
        name: "Элайджа Вуд",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Elijah_Wood_by_Gage_Skidmore_3.jpg/500px-Elijah_Wood_by_Gage_Skidmore_3.jpg"
      },
      {
        name: "Иэн Маккеллен",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/McKellenRichmnd040219-5_%2846275370484%29_%28cropped%29.jpg/500px-McKellenRichmnd040219-5_%2846275370484%29_%28cropped%29.jpg"
      },
      {
        name: "Вигго Мортенсен",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Viggo_Mortensen_B_%282020%29.jpg/500px-Viggo_Mortensen_B_%282020%29.jpg"
      },
      {
        name: "Орландо Блум",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Orlando_Bloom_at_the_2024_Toronto_International_Film_Festival_%28cropped2%29.jpg/500px-Orlando_Bloom_at_the_2024_Toronto_International_Film_Festival_%28cropped2%29.jpg"
      },
      {
        name: "Шон Бин",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Sean_Bean_Anemone-25_%28cropped%29.jpg/500px-Sean_Bean_Anemone-25_%28cropped%29.jpg"
      },
      {
        name: "Кейт Бланшетт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Cate_Blanchett-63298_%28cropped_2%29.jpg/500px-Cate_Blanchett-63298_%28cropped_2%29.jpg"
      }
    ]
  },
  {
    id: "pulp-fiction",
    title: "Криминальное чтиво",
    aliases: [
      "Pulp Fiction"
    ],
    cast: [
      {
        name: "Джон Траволта",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/John_Travolta_Cannes_2018_%28cropped%29.jpg"
      },
      {
        name: "Сэмюэл Л. Джексон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SamuelLJackson.jpg/500px-SamuelLJackson.jpg"
      },
      {
        name: "Ума Турман",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/UmaThurman-byPhilipRomano.jpg/500px-UmaThurman-byPhilipRomano.jpg"
      },
      {
        name: "Брюс Уиллис",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Bruce_Willis_by_Gage_Skidmore_3.jpg/500px-Bruce_Willis_by_Gage_Skidmore_3.jpg"
      },
      {
        name: "Тим Рот",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Tim_Roth_by_Gage_Skidmore_2.jpg/500px-Tim_Roth_by_Gage_Skidmore_2.jpg"
      },
      {
        name: "Винг Реймс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Ving_Rhames_2010_%284710601891%29_%28cropped%29.jpg"
      }
    ]
  },
  {
    id: "forrest-gump",
    title: "Форрест Гамп",
    aliases: [
      "Forrest Gump"
    ],
    cast: [
      {
        name: "Том Хэнкс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg/500px-TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg"
      },
      {
        name: "Робин Райт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Robin_Wright_Cannes_2017_%28cropped%29.jpg"
      },
      {
        name: "Гэри Синиз",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/GarySiniseOct09.jpg/500px-GarySiniseOct09.jpg"
      },
      {
        name: "Майкелти Уильямсон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Mykelti_Williamson_%2831627443022%29.jpg/500px-Mykelti_Williamson_%2831627443022%29.jpg"
      },
      {
        name: "Салли Филд",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Sally_Field_%2811205%29_%28cropped%29.jpg/500px-Sally_Field_%2811205%29_%28cropped%29.jpg"
      }
    ]
  },
  {
    id: "titanic",
    title: "Титаник",
    aliases: [
      "Titanic"
    ],
    cast: [
      {
        name: "Леонардо ДиКаприо",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/LeoPTABFI191125-28_%28cropped%29.jpg/500px-LeoPTABFI191125-28_%28cropped%29.jpg"
      },
      {
        name: "Кейт Уинслет",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/KateWinslet_%28cropped%29.jpg/500px-KateWinslet_%28cropped%29.jpg"
      },
      {
        name: "Билли Зейн",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Billy_Zane_Photo_Op_GalaxyCon_Raleigh_2025_%28cropped%29.jpg/500px-Billy_Zane_Photo_Op_GalaxyCon_Raleigh_2025_%28cropped%29.jpg"
      },
      {
        name: "Кэти Бейтс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kathy_Bates_by_Gage_Skidmore.jpg/500px-Kathy_Bates_by_Gage_Skidmore.jpg"
      },
      {
        name: "Билл Пэкстон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Bill_Paxton_by_Gage_Skidmore_2.jpg/500px-Bill_Paxton_by_Gage_Skidmore_2.jpg"
      }
    ]
  },
  {
    id: "back-to-the-future",
    title: "Назад в будущее",
    aliases: [
      "Back to the Future",
      "Назад в будущее 1"
    ],
    cast: [
      {
        name: "Майкл Дж. Фокс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Michael_J_Fox_2020.jpg/500px-Michael_J_Fox_2020.jpg"
      },
      {
        name: "Кристофер Ллойд",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/ChristopherLloyd2022.jpg/500px-ChristopherLloyd2022.jpg"
      },
      {
        name: "Лиа Томпсон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lea_Thompson_%2853319047148%29.jpg/500px-Lea_Thompson_%2853319047148%29.jpg"
      },
      {
        name: "Криспин Гловер",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Crispin_Glover_cropped_2010.jpg/500px-Crispin_Glover_cropped_2010.jpg"
      },
      {
        name: "Томас Уилсон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Tom_Wilson_photo_by_Josh_Alder.jpg/500px-Tom_Wilson_photo_by_Josh_Alder.jpg"
      }
    ]
  },
  {
    id: "avengers-endgame",
    title: "Мстители: Финал",
    aliases: [
      "Avengers: Endgame",
      "Мстители Финал"
    ],
    cast: [
      {
        name: "Роберт Дауни мл.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Robert_Downey_Jr._-_2019_Disney_Legends_Awards_Ceremony_-_D23_EXPO_2019_%28cropped%29.jpg/500px-Robert_Downey_Jr._-_2019_Disney_Legends_Awards_Ceremony_-_D23_EXPO_2019_%28cropped%29.jpg"
      },
      {
        name: "Крис Эванс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Chris_Evans_at_the_2025_Toronto_International_Film_Festival_%28cropped%29.jpg/500px-Chris_Evans_at_the_2025_Toronto_International_Film_Festival_%28cropped%29.jpg"
      },
      {
        name: "Скарлетт Йоханссон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Scarlett_Johansson-8588.jpg/500px-Scarlett_Johansson-8588.jpg"
      },
      {
        name: "Крис Хемсворт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Chris_Hemsworth_by_Gage_Skidmore_3.jpg/500px-Chris_Hemsworth_by_Gage_Skidmore_3.jpg"
      },
      {
        name: "Марк Руффало",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Mark_Ruffalo_%2836201774756%29_%28cropped%29.jpg/500px-Mark_Ruffalo_%2836201774756%29_%28cropped%29.jpg"
      },
      {
        name: "Джереми Реннер",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Jeremy_Renner_at_TIFF_2025_%28cropped%29.jpg/500px-Jeremy_Renner_at_TIFF_2025_%28cropped%29.jpg"
      }
    ]
  },
  {
    id: "gladiator",
    title: "Гладиатор",
    aliases: [
      "Gladiator"
    ],
    cast: [
      {
        name: "Расселл Кроу",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Russell_Crowe_on_the_Green_Carpet_at_the_2025_Zurich_Film_Festival_06_%28cropped%29.jpg/500px-Russell_Crowe_on_the_Green_Carpet_at_the_2025_Zurich_Film_Festival_06_%28cropped%29.jpg"
      },
      {
        name: "Хоакин Феникс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Joaquin_Phoenix-64908_%28cropped%29.jpg/500px-Joaquin_Phoenix-64908_%28cropped%29.jpg"
      },
      {
        name: "Конни Нильсен",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Connie_Nielsen_by_Gage_Skidmore.jpg/500px-Connie_Nielsen_by_Gage_Skidmore.jpg"
      },
      {
        name: "Джимон Хонсу",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Djimon_Hounsou_by_Gage_Skidmore_2.jpg/500px-Djimon_Hounsou_by_Gage_Skidmore_2.jpg"
      },
      {
        name: "Ричард Харрис",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Richard_Harris_1985.jpg/500px-Richard_Harris_1985.jpg"
      }
    ]
  },
  {
    id: "fight-club",
    title: "Бойцовский клуб",
    aliases: [
      "Fight Club"
    ],
    cast: [
      {
        name: "Брэд Питт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Brad_Pitt-69858.jpg/500px-Brad_Pitt-69858.jpg"
      },
      {
        name: "Эдвард Нортон",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Ed_Norton_and_Shauna_Robertson_TIFF_2025_%28cropped%29.jpg/500px-Ed_Norton_and_Shauna_Robertson_TIFF_2025_%28cropped%29.jpg"
      },
      {
        name: "Хелена Бонэм Картер",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Helena_Bonham_Carter_2011_AA.jpg/500px-Helena_Bonham_Carter_2011_AA.jpg"
      },
      {
        name: "Джаред Лето",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Jared_Leto_by_Gage_Skidmore_2.jpg/500px-Jared_Leto_by_Gage_Skidmore_2.jpg"
      }
    ]
  },
  {
    id: "dark-knight",
    title: "Тёмный рыцарь",
    aliases: [
      "The Dark Knight",
      "Темный рыцарь"
    ],
    cast: [
      {
        name: "Кристиан Бейл",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/MJK_35690_Christian_Bale_%28Vice%2C_Berlinale_2019%29.jpg/500px-MJK_35690_Christian_Bale_%28Vice%2C_Berlinale_2019%29.jpg"
      },
      {
        name: "Хит Леджер",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Heath_Ledger_%28Berlin_Film_Festival_2006%29_revised.jpg/500px-Heath_Ledger_%28Berlin_Film_Festival_2006%29_revised.jpg"
      },
      {
        name: "Аарон Экхарт",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Aaron_Eckhart_%2829830286295%29_%28cropped%29.jpg/500px-Aaron_Eckhart_%2829830286295%29_%28cropped%29.jpg"
      },
      {
        name: "Майкл Кейн",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sir_Michael_Caine%2C_28th_EFA_Awards_2015%2C_Berlin_%28cropped%29.jpg"
      },
      {
        name: "Морган Фриман",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg/500px-Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg"
      },
      {
        name: "Мэгги Джилленхол",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Maggie_Gyllenhaal_2021.jpg/500px-Maggie_Gyllenhaal_2021.jpg"
      }
    ]
  },
  {
    id: "ivan-vasilievich",
    title: "Иван Васильевич меняет профессию",
    aliases: [
      "Иван Васильевич",
      "Ivan Vasilievich Changes Profession"
    ],
    cast: [
      {
        name: "Юрий Яковлев",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Yury_Yakovlev_%28cropped%29.jpg"
      },
      {
        name: "Леонид Куравлёв",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Kuravlev_%28cropped%29.jpg/500px-Kuravlev_%28cropped%29.jpg"
      },
      {
        name: "Наталья Селезнёва",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Natalya_Seleznyova1.jpg/500px-Natalya_Seleznyova1.jpg"
      }
    ]
  },
  {
    id: "brat",
    title: "Брат",
    aliases: [
      "Brat"
    ],
    cast: [
      {
        name: "Виктор Сухоруков",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Viktor_Sukhorukov.jpg/500px-Viktor_Sukhorukov.jpg"
      },
      {
        name: "Юрий Кузнецов",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Yuri_Kuznetsov.jpg/500px-Yuri_Kuznetsov.jpg"
      }
    ]
  },
  {
    id: "leon",
    title: "Леон",
    aliases: [
      "Léon: The Professional",
      "Leon",
      "Леон: Киллер"
    ],
    cast: [
      {
        name: "Жан Рено",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Jean_Reno_Cannes_2016.jpg/500px-Jean_Reno_Cannes_2016.jpg"
      },
      {
        name: "Натали Портман",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/NataliePortman.jpg/500px-NataliePortman.jpg"
      },
      {
        name: "Гэри Олдмен",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Gary_Oldman_by_Gage_Skidmore.jpg/500px-Gary_Oldman_by_Gage_Skidmore.jpg"
      },
      {
        name: "Дэнни Айелло",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/Danny_Aiello.jpg"
      }
    ]
  },
  {
    id: "shrek",
    title: "Шрек",
    aliases: [
      "Shrek"
    ],
    cast: [
      {
        name: "Майк Майерс",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mike_Myers_2017_%2837220071326%29_%28cropped%29.jpg/500px-Mike_Myers_2017_%2837220071326%29_%28cropped%29.jpg"
      },
      {
        name: "Эдди Мёрфи",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Eddie_Murphy_by_David_Shankbone.jpg/500px-Eddie_Murphy_by_David_Shankbone.jpg"
      },
      {
        name: "Камерон Диас",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Cameron_Diaz_at_WWD_Style_Awards_2026-1998.jpg/500px-Cameron_Diaz_at_WWD_Style_Awards_2026-1998.jpg"
      },
      {
        name: "Джон Литгоу",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/John_Lithgow_at_Met_Opera_Opening_in_2008.jpg/500px-John_Lithgow_at_Met_Opera_Opening_in_2008.jpg"
      }
    ]
  }
];

// Normalize a string for fuzzy comparison: lowercase, strip whitespace and
// punctuation, replace ё→е, and remove anything that's not a letter or digit.
export function normalizeAnswer(text: string): string {
  return text
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/[^a-zа-я0-9]/gi, '');
}

export function answerMatches(text: string, movie: Movie): boolean {
  const normalized = normalizeAnswer(text);
  if (!normalized) return false;
  const candidates = [movie.title, ...movie.aliases];
  for (const c of candidates) {
    const n = normalizeAnswer(c);
    if (!n) continue;
    if (n === normalized) return true;
    if (n.length >= 4 && normalized.includes(n)) return true;
    if (normalized.length >= 4 && n.includes(normalized)) return true;
  }
  return false;
}

export function pickMovies(source: Movie[], count: number, exclude: Set<string>): Movie[] {
  const pool = source.filter(m => !exclude.has(m.id));
  const list = pool.length >= count ? pool : source.slice();
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list.slice(0, count);
}
